### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by benryandev** [tuanle618/neural-net-random-art#1]
Would it be possible to output this as a animation using matplotlib? I think it would be extremely interesting to see the change via a animation. The black and white would be like liquid metal flowing.

**Comment by benryandev** [comment]
Any assistance or shove in the right direction would be super

**Comment by dariox2** [comment]
Hi @benryandev,
You need to apply small, gradual changes to the NN parameters between each generated image inside the loop

Example:

https://user-images.githubusercontent.com/4793667/151682544-8da191ce-0c23-4c6c-922b-f171e18f2a39.mp4

.

**Comment by tuanle618** [comment]
That's what I thought as well, @dariox2.
I've updated the main branch and stored all the neural networks layers in the `FeedForwardNet.layers` list.
So it should be straightforward to change the parameters slightly, e.g., see how the weights are randomly initialized.
https://github.com/tuanle618/neural-net-random-art/blob/434bc0a4157dc4666e598c5616f8fa4a2f549122/nnetart/network.py#L16-L21

To gradually change, one could apply some operations for each `self.layers[i].weight.data` tensor.
Note that the layers now also include a `bias` term. You can set if off, by just setting `bias=False` in the layer init.

**Comment by benryandev** [comment]
> Hi @benryandev, You need to apply small, gradual changes to the NN parameters between each generated image inside the loop
> 
> Example:
> 
>  out.mp4 
> 
> .

Hey @dariox2 . Could you please. share with me how you achieved this. It's doing my head in trying to work it out.

**Comment by benryandev** [comment]
@dariox2 @tuanle618 Here is a Matplotlib animation tutorial I found but I having trouble applying it to this.
https://jakevdp.github.io/blog/2012/08/18/matplotlib-animation-tutorial/
May I please get your assistance in creating this animation? I'm so sorry to ask, but I've hit a wall on my end.

**Comment by tuanle618** [comment]
Hey @benryandev 
I've created a Google Colab notebook for the animation of generated images. You might want to experiment with different noise levels to be added when creating a new image in the for-loop.

Link: https://colab.research.google.com/drive/1Jdmvh72NsQlb0GdXdhgBDMfiNm5Q8WUe?usp=sharing

Edit: Here the video, created in the colab notebook.

https://user-images.githubusercontent.com/33153559/157042750-0ac4bf05-3bd8-4027-a338-55233745ed01.mp4

**Comment by tuanle618** [comment]
Closing this issue. Feel free to reopen in case you have further questions, @benryandev .
