### ISSUE TITLE
Using Google Cololab - Issue missing module 

### ISSUE THREAD

**Issue by Techfluent-au** [tuanle618/neural-net-random-art#5]
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-5-30065a771e4a>](https://localhost:8080/#) in <module>()
----> 1 from nnetart.network import FeedForwardNetwork

ModuleNotFoundError: No module named 'nnetart'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by tuanle618** [comment]
Hey, I will create a minimal working example colab notebook the upcoming days and let you know once its done.

**Comment by Techfluent-au** [comment]
@tuanle618 

Hope you are well, How is the working example coming along? Appreciate your efforts

**Comment by tuanle618** [comment]
Hi @Techfluent-au , I'm gonna have a look into this and let you know. Sorry for the delay

**Comment by tuanle618** [comment]
Hi @Techfluent-au ,

I've created a minimal example colab notebook here: https://colab.research.google.com/drive/1TFmQQOUHOPjSrB0dVeoYiD7d7FPidilW?usp=sharing

Please copy this file to your gdrive and try to run it. Let me know if you have further questions.

**Comment by Techfluent-au** [comment]
> Hi @Techfluent-au ,
> 
> I've created a minimal example colab notebook here: https://colab.research.google.com/drive/1TFmQQOUHOPjSrB0dVeoYiD7d7FPidilW?usp=sharing
> 
> Please copy this file to your gdrive and try to run it. Let me know if you have further questions.
> 

Thanks @tuanle618 ,

That's awesome 👌,  worked first go. 👏 your AI generation tool is amazing. 

We had a storm knock out our Broadband Network modem last night, once we get a new one I'll study to tool and how it works and come back to you if you I have any questions or suggestions. 

Many thanks

**Comment by tuanle618** [comment]
Glad to hear.
I'll close this issue. Feel free to reopen again, if you have further questions.
