### ISSUE TITLE
random_art.py: error: unrecognized arguments: -image_width 512

### ISSUE THREAD

**Issue by Techfluent-au** [tuanle618/neural-net-random-art#6]
(base) C:\Users\npall\Desktop\neural>python random_art.py -img_height 512 -image_width 512 -colormode bw -alpha False -n_images 5
usage: random_art.py [-h] [-img_height] [-img_width] [-colormode] [-alpha] [-n_images] [-n_depth] [-n_size]
                     [-activation] [-z1] [-z2] [-trig] [-noise] [-noise_std] [-sym] [-gpu] [-format]
random_art.py: error: unrecognized arguments: -image_width 512

**Comment by tuanle618** [comment]
That argument `--image_width` is not used in the ArgumentParser.
The required argument is `--img_width` .
